## Pytorch Fundamentals

In [2]:
print("testing python working")

testing python working


In [3]:
import torch
import pandas as pd
import matplotlib as plt
import numpy as np

print(torch.__version__)

2.5.1


# intro to tensor

In [6]:
scaler = torch.tensor(7)
print(scaler)
print(scaler.ndim)
print(scaler.shape)
print(scaler.item())

tensor(7)
0
torch.Size([])
7


In [8]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [13]:
matrix = torch.tensor([[1,2], [3,4]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix[1])
print(matrix[1][1])

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])
tensor([3, 4])
tensor(4)


In [ ]:
tensor = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
print(tensor.ndim)
print(tensor.shape)
print(tensor[0])
print(tensor[0][1])
print(tensor[0][1][2])
print(tensor.size)

3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([4, 5, 6])
tensor(6)
torch.Size([1, 3, 3])


In [ ]:
tensor = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(tensor.ndim)
print(tensor.shape)
print(tensor[0])
print(tensor[0][1])

2
torch.Size([3, 3])
tensor([1, 2, 3])
tensor(2)


### Random tensors

random numbers -> look at data -> update random number -> look again -> update again -> repeat


In [ ]:
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[0.5492, 0.0906, 0.1448, 0.9041],
        [0.6809, 0.3094, 0.6872, 0.5560],
        [0.2010, 0.8711, 0.3170, 0.7031]])
2


In [22]:
random_image_tensor = torch.rand(size=(224, 224, 3))
print(random_image_tensor.shape)
print(random_image_tensor.ndim)

torch.Size([224, 224, 3])
3


### zeros and ones

In [25]:
zeros = torch.zeros(3, 4)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [27]:
ones = torch.ones(3, 4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### createing a range of tensors and tensors like

In [37]:
# start, end, step, it is going to finish at end - 1

arange = torch.arange(0, 10)
print(arange)
print(arange.ndim)
print(arange.shape)

like_zeros = torch.zeros_like(input=arange)
print(like_zeros)
print(like_zeros.ndim)
print(like_zeros.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
1
torch.Size([10])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
1
torch.Size([10])


### tensor datatype

In [41]:
float_16 = torch.tensor([3,0, 6.0, 9.0], dtype=torch.float16, device="cpu", requires_grad=False)
print(float_16.dtype)

torch.float16
